apiVersion: apps/v1
kind: Deployment
metadata:
  name: cocktail-service
  labels:
    app: cocktail-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cocktail-service
  template:
    metadata:
      labels:
        app: cocktail-service
    spec:
      containers:
        - name: cocktail-service
          # À adapter avec le nom de ton image si différent
          image: destryke/cocktail-service:latest
          ports:
            - containerPort: 3001
          env:
            - name: DATABASE_URL
              value: "postgresql://user:password@cocktail-postgres:5432/cocktail_db"
            - name: JWT_SECRET
              value: "super-secret-key"
            - name: PORT
              value: "3001"
          livenessProbe:
            httpGet:
              path: /cocktail
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /cocktail
              port: 3001
            initialDelaySeconds: 2
            periodSeconds: 5

